language: php
php:
  - 5.5
  - 5.6
  - 7.0
addons:
  code_climate:
    repo_token: SET_ME
before_script:
  - sed -i '/phpdocumentor/d' composer.json
  - composer install
script:
  - phpunit --configuration test/phpunit.xml test
  - ./vendor/bin/phpcs --ignore=*/vendor/*,*/test/*,*/bin/* --standard=./vendor/uwdoem/standard/ruleset.xml .
  - ./vendor/bin/phpcs --standard=PSR2 test
after_script:
  - vendor/bin/test-reporter
